language:
  - node_js
node_js:
  - "7"
env:
  - CXX=g++-5
sudo:
  - required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
before_script:
  - npm start
after_success:
  - npm run codecov
