language:
  - node_js
node_js:
  - "7"
env:
  - CXX=g++-5 PROTOCOL=http HOST=localhost PORT=3000 DB_NAME=memowise DB_HOST=localhost DB_PORT=27017 SESSION_SECRET=memowise NODE_ENV=development
sudo:
  - required
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
before_install:
  - npm install -g node-gyp
before_script:
  - sleep 15
  - npm start &
after_success:
  - npm run codecov
